name: Threatspec
    

on:
  push:
    paths:
      - '.github/threatmodel/threatmodel'
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
    paths:
      - '.github/threatmodel/threatmodel'

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check for specific file
        run: |
          if [[ $(git diff-tree --no-commit-id --name-only -r ${{ github.sha }}) =~ ".github/threatmodel/threatmodel" ]]; then
            echo "Specific file found. Starting build..."
          else
            echo "Specific file not found. Skipping build."
            exit 78
          fi
        
      - name: Run a multi-line script
        run: |
          git clone https://github.com/threatspec/threatspec.git
          cd threatspec
          pip install threatspec
          cd ..
          threatspec init
          threatspec run
      - uses: actions/upload-artifact@v1
        with:
         name: threatmodel.json
         path: ./threatmodel/

          
          
          
