name: Threatspec
    

on:
  push:
    paths:
      - '.github/threatmodel/threatmodel.txt'
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
    paths:
      - '.github/threatmodel/threatmodel.txt'

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        
      - name: Run a multi-line script
        run: |
          git clone https://github.com/threatspec/threatspec.git
          cd threatspec
          pip install threatspec
          cd ../.github/threatmodel/
          pwd
          ls
          threatspec init
          threatspec run
          pwd
          ls -la
      - uses: actions/upload-artifact@v1
        with:
         name: threatmodel.json
         path: ./.github/threatmodel

          
          
          
