name: VerifyThreatModelling
inputs:
  src:
    description: "Source directory to scan. Defaults to workspace"
    required: false
    default: "/github/workspace"
  output:
    description: "Output directory for the generated reports. Defaults to reports"
    required: false
    default: "/github/workspace/reports"

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  workflow_dispatch:

jobs:

  build:
    
    runs-on: ubuntu-latest
    
    steps:
      
      - name: Run a multi-line script
        run: |
          git clone https://github.com/threatspec/threatspec.git
          cd threatspec
          pip install threatspec
          cd ..
          threatspec init
          threatspec run
          threatsspec report
          
          
          
